version: '3'

volumes:
  db-volume:

services:
  php:
    container_name: cms
    build: ./docker/php
    volumes:
      - ./backend:/var/www/html
    environment:
      TZ: Asia/Tokyo

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    volumes:
      - db-volume:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - "4306:3306"